spring.application.name=agrawalJewelers
server.port=8001
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=agrawalJewelers
spring.data.mongodb.uri=mongodb+srv://agrawalkrishna7114_db_user:slErBAUgqKv9VXSv@cluster0.8fdjwzl.mongodb.net/?appName=Cluster0
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
